package ebookBackend.dao;

import java.util.List;

import ebookBackend.entity.BookDetail;
import ebookBackend.entity.BookDetailWithBLOBs;
import ebookBackend.entity.BookDetailExample;
import org.apache.ibatis.annotations.Param;

public interface TBookDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int countByExample(BookDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int deleteByExample(BookDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int insert(BookDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int insertSelective(BookDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    List<BookDetailWithBLOBs> selectByExampleWithBLOBs(BookDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    List<BookDetail> selectByExample(BookDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookDetailWithBLOBs record, @Param("example") BookDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BookDetailWithBLOBs record, @Param("example") BookDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookDetail record, @Param("example") BookDetailExample example);
}