package ebookBackend.dao;

import ebookBackend.entity.CartItems;
import ebookBackend.entity.CartItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_items
     *
     * @mbggenerated
     */
    int countByExample(CartItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_items
     *
     * @mbggenerated
     */
    int deleteByExample(CartItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_items
     *
     * @mbggenerated
     */
    int insert(CartItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_items
     *
     * @mbggenerated
     */
    int insertSelective(CartItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_items
     *
     * @mbggenerated
     */
    List<CartItems> selectByExample(CartItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_items
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CartItems record, @Param("example") CartItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_items
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CartItems record, @Param("example") CartItemsExample example);
}