package ebookBackend.dao;

import ebookBackend.entity.TBookdetail;
import ebookBackend.entity.TBookdetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBookdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int countByExample(TBookdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int deleteByExample(TBookdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int insert(TBookdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int insertSelective(TBookdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    List<TBookdetail> selectByExample(TBookdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TBookdetail record, @Param("example") TBookdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookdetail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TBookdetail record, @Param("example") TBookdetailExample example);
}