package ebookBackend.dao;

import ebookBackend.entity.TBooklist;
import ebookBackend.entity.TBooklistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBooklistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_booklist
     *
     * @mbggenerated
     */
    int countByExample(TBooklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_booklist
     *
     * @mbggenerated
     */
    int deleteByExample(TBooklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_booklist
     *
     * @mbggenerated
     */
    int insert(TBooklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_booklist
     *
     * @mbggenerated
     */
    int insertSelective(TBooklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_booklist
     *
     * @mbggenerated
     */
    List<TBooklist> selectByExample(TBooklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_booklist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TBooklist record, @Param("example") TBooklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_booklist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TBooklist record, @Param("example") TBooklistExample example);
}