package ebookBackend.dao;

import ebookBackend.entity.TItems;
import ebookBackend.entity.TItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items
     *
     * @mbggenerated
     */
    int countByExample(TItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items
     *
     * @mbggenerated
     */
    int deleteByExample(TItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items
     *
     * @mbggenerated
     */
    int insert(TItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items
     *
     * @mbggenerated
     */
    int insertSelective(TItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items
     *
     * @mbggenerated
     */
    List<TItems> selectByExample(TItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TItems record, @Param("example") TItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TItems record, @Param("example") TItemsExample example);
}