package ebookBackend.entity;

public class BookDetailWithBLOBs extends BookDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookdetail.abstraction
     *
     * @mbggenerated
     */
    private String abstraction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookdetail.catalogue
     *
     * @mbggenerated
     */
    private String catalogue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookdetail.abstraction
     *
     * @return the value of t_bookdetail.abstraction
     *
     * @mbggenerated
     */
    public String getAbstraction() {
        return abstraction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookdetail.abstraction
     *
     * @param abstraction the value for t_bookdetail.abstraction
     *
     * @mbggenerated
     */
    public void setAbstraction(String abstraction) {
        this.abstraction = abstraction == null ? null : abstraction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookdetail.catalogue
     *
     * @return the value of t_bookdetail.catalogue
     *
     * @mbggenerated
     */
    public String getCatalogue() {
        return catalogue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookdetail.catalogue
     *
     * @param catalogue the value for t_bookdetail.catalogue
     *
     * @mbggenerated
     */
    public void setCatalogue(String catalogue) {
        this.catalogue = catalogue == null ? null : catalogue.trim();
    }
}