package ebookBackend.entity;

import java.math.BigDecimal;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total
     *
     * @mbggenerated
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.userID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderID
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total
     *
     * @return the value of order.total
     *
     * @mbggenerated
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total
     *
     * @param total the value for order.total
     *
     * @mbggenerated
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.userID
     *
     * @return the value of order.userID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.userID
     *
     * @param userid the value for order.userID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderID
     *
     * @return the value of order.orderID
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderID
     *
     * @param orderid the value for order.orderID
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
}